version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    cooldown:
      default-days: 7
