nodeLinker: pnp

packageExtensions:
  "@commitlint/load@*":
    dependencies:
      "@types/node": "^24.0.0"
      typescript: "6.0.3"
  "eslint-plugin-perfectionist@*":
    dependencies:
      typescript: "6.0.3"
