import type { Preset } from "../types";

export const web3Preset: Preset = {
  name: `web3`,
  description: `Conservative checks for common web3 toolchains under Yarn PnP.`,
  watchRules: [
    {
      ident: `hardhat`,
      severity: `warning`,
      code: `WEB3_HARDHAT_STACK`,
      title: `Hardhat stack detected`,
      message: `Hardhat projects often combine plugin peer dependencies, generated artifacts, and older packages that assume a loose node_modules layout.`,
      recommendation: `Run the project test/build command after install and turn any undeclared dependency crash into a packageExtensions rule.`,
    },
    {
      ident: `@nomicfoundation/hardhat-toolbox`,
      severity: `warning`,
      code: `WEB3_HARDHAT_TOOLBOX`,
      title: `Hardhat toolbox detected`,
      message: `Toolbox packages aggregate several Hardhat plugins and are a good place to check peer requirements and virtual package churn.`,
      recommendation: `Prefer explicit direct dependencies for the plugins you use and keep package extension fixes scoped to the package that imports them.`,
    },
    {
      ident: `@nomiclabs/hardhat-ethers`,
      severity: `warning`,
      code: `WEB3_LEGACY_HARDHAT_ETHERS`,
      title: `Legacy Hardhat ethers plugin detected`,
      message: `Older Hardhat ethers integrations are common in projects that mix ethers major versions and stale plugin assumptions.`,
      recommendation: `Check whether the project should be on @nomicfoundation/hardhat-ethers and keep ethers majors aligned across workspaces.`,
    },
    {
      ident: `@walletconnect/ethereum-provider`,
      severity: `info`,
      code: `WEB3_WALLETCONNECT_PROVIDER`,
      title: `WalletConnect provider detected`,
      message: `WalletConnect stacks pull browser, crypto, and RPC packages through several transitive layers, which makes PnP failures harder to trace manually.`,
      recommendation: `Inspect runtime crashes for undeclared imports from transitive packages and add only the missing packageExtension entries.`,
    },
    {
      ident: `@solana/web3.js`,
      severity: `info`,
      code: `WEB3_SOLANA_STACK`,
      title: `Solana client stack detected`,
      message: `Solana client packages often sit near native or binary-adjacent packages that deserve extra attention under strict installs.`,
      recommendation: `If binary loading fails from inside Yarn cache archives, verify whether the affected package needs to be unplugged.`,
    },
    {
      ident: `@wagmi/cli`,
      severity: `info`,
      code: `WEB3_CODEGEN_STACK`,
      title: `Web3 codegen stack detected`,
      message: `Code generation packages can hide stale ABI, generated client, and peer dependency problems until build time.`,
      recommendation: `Run codegen in CI after install and add package extension rules for undeclared imports discovered there.`,
    },
  ],
  packageExtensionRules: [],
  majorAlignmentIdents: [`ethers`, `viem`, `wagmi`, `hardhat`, `@solana/web3.js`],
  nativeBinaryIdents: [
    `@esbuild/darwin-arm64`,
    `@esbuild/darwin-x64`,
    `@esbuild/linux-arm64`,
    `@esbuild/linux-x64`,
    `@swc/core`,
    `bigint-buffer`,
    `bufferutil`,
    `keccak`,
    `node-gyp-build`,
    `prebuild-install`,
    `secp256k1`,
    `utf-8-validate`,
  ],
};
