name: GitHub Actions Security Analysis with zizmor

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e
        with:
          advanced-security: false
          min-severity: medium
          min-confidence: medium
